### PR TITLE
Add missed fallback to generic language (in `LanguageNegotiator`)

### PR DESCRIPTION
**Pull request by rtm-ctrlz**
Same fix as #65 but for current version

### CODE REVIEW

**Comment by Seb33300** [comment]
@rtm-ctrlz is it a fix for https://github.com/willdurand/Negotiation/issues/102?

**Comment by rtm-ctrlz** [comment]
@Seb33300 yes, this PR should fix it

**Comment by Seb33300** [comment]
Ping @willdurand, if you could merge this PR it could be very helpfull since branch 2.x doesn't support PHP 8 so we cannot rely on it anymore.

BTW, this will fix all of the language related issues: #103, #102, #80

**Comment by willdurand** [comment]
Super sorry for not having merged this patch earlier.. I'll release a new version soon.

**Comment by willdurand** [comment]
https://github.com/willdurand/Negotiation/releases/tag/3.1.0

**Pull request merged**
