### PR TITLE
Fix incompatibilities with some null values for PHP 8.1

### LINKED ISSUE #115: Deprecation notices with PHP 8.1
```
❯ ./vendor/bin/simple-phpunit --verbose
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.2
Configuration: /Users/william/projects/Negotiation/phpunit.xml.dist

[...]

Remaining self deprecation notices (76)

  38x: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated
    34x in LanguageNegotiatorTest::testGetBest from Negotiation\Tests
    4x in LanguageNegotiatorTest::testGetBestRespectsQualityOfSource from Negotiation\Tests

  37x: strcasecmp(): Passing null to parameter #2 ($string2) of type string is deprecated
    33x in LanguageNegotiatorTest::testGetBest from Negotiation\Tests
    4x in LanguageNegotiatorTest::testGetBestRespectsQualityOfSource from Negotiation\Tests

  1x: explode(): Passing null to parameter #2 ($string) of type string is deprecated
    1x in AcceptLanguageTest::testGetType from Negotiation\Tests

```

### PR DESCRIPTION
**Pull request by W0rma**
Fixes #115

### CODE REVIEW

**Comment by usox** [comment]
@willdurand sorry to disturb but are there any chances of getting this merged soon?

**Comment by mnapoli** [comment]
This is indeed blocking PHP 8.1 support for me as well.

**Comment by ElisDN** [comment]
@willdurand sorry to disturb but are there any chances of getting this merged soon?

**Comment by alexandrbarabolia** [comment]
@willdurand please accept pr

**Comment by willdurand** [comment]
ha, oops. Let me see. I am not too much into GitHub actions so I'll need to take a closer look at ths proposed changes (or see if I can use Circle instead).

IIUC the actual 8.1 incompatibilities are related to some functions not accepting non-string params anymore?

**Comment by ElisDN** [comment]
> IIUC the actual 8.1 incompatibilities are related to some functions not accepting non-string params anymore?

Yes, `strcasecmp` is not accepting `null` value now.

**Comment by usox** [comment]
> ha, oops. Let me see. I am not too much into GitHub actions so I'll need to take a closer look at ths proposed changes (or see if I can use Circle instead).

If it helps: From my pov, the action is looking good so far.

> IIUC the actual 8.1 incompatibilities are related to some functions not accepting non-string params anymore?

Exactly. _maybe_ a string cast would also do the trick.

**Comment by willdurand** [comment]
alright, so I moved the second commit to its own PR (see: https://github.com/willdurand/Negotiation/pull/116) given it isn't strictly related to PHP 8.1. I filed an issue for these incompatibilities here: #115.

**Comment by willdurand** [comment]
hey @W0rma, thanks for your patch. Could you please rebase your PR so that CI can run? I cherry-picked your second commit and landed it on the main branch already.

**Comment by willdurand** [comment]
Nevermind, I can do it myself. You waited long enough on me to review this PR so let me finish the work here.

**Comment by willdurand** [comment]
https://github.com/willdurand/Negotiation/releases/tag/3.1.0 (please test it)

**Pull request merged**
